// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO8JifjAZ7UDChKCKwxd5apBbSMNFLkH4',
    appId: '1:215643034568:web:fcccbbf80ac8e601bb66fd',
    messagingSenderId: '215643034568',
    projectId: 'skilltok-bf45d',
    authDomain: 'skilltok-bf45d.firebaseapp.com',
    storageBucket: 'skilltok-bf45d.firebasestorage.app',
    measurementId: 'G-FYD8MTF7G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkgsTRd0U4kmEvdNgSeP9s6NDcMpmG0b4',
    appId: '1:215643034568:android:e41975063f9cad1cbb66fd',
    messagingSenderId: '215643034568',
    projectId: 'skilltok-bf45d',
    storageBucket: 'skilltok-bf45d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB8ZKqJKPHORVO3Gp0lyRyX2TyROLko8Q',
    appId: '1:215643034568:ios:40740882158f16b2bb66fd',
    messagingSenderId: '215643034568',
    projectId: 'skilltok-bf45d',
    storageBucket: 'skilltok-bf45d.firebasestorage.app',
    iosBundleId: 'com.example.skilltok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB8ZKqJKPHORVO3Gp0lyRyX2TyROLko8Q',
    appId: '1:215643034568:ios:40740882158f16b2bb66fd',
    messagingSenderId: '215643034568',
    projectId: 'skilltok-bf45d',
    storageBucket: 'skilltok-bf45d.firebasestorage.app',
    iosBundleId: 'com.example.skilltok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO8JifjAZ7UDChKCKwxd5apBbSMNFLkH4',
    appId: '1:215643034568:web:b3631834bb3cbfb5bb66fd',
    messagingSenderId: '215643034568',
    projectId: 'skilltok-bf45d',
    authDomain: 'skilltok-bf45d.firebaseapp.com',
    storageBucket: 'skilltok-bf45d.firebasestorage.app',
    measurementId: 'G-T1P8R5MDK2',
  );
}
